version: 2
updates:
    -   package-ecosystem: "github-actions"
        directory: "/" 
        schedule:
            interval: "weekly"
    -   package-ecosystem: "nuget"
        directory: "/src/"
        schedule:
            interval: "weekly"
        groups:
            Microsoft.Extensions:
                applies-to: version-updates
                patterns:
                    - "Microsoft.Extensions.*"
            NUnit:
                applies-to: version-updates
                patterns:
                    - "nunit*"
